name:                pandoc-filter-indent
version:             0.2.3.0
github:              "mgajda/pandoc-filter-indent"
license:             BSD3
author:              "Michał J. Gajda"
maintainer:          "mjgajda@migamake.com"
copyright:           "AllRightsReserved"
category:            Text
synopsis:            "Pandoc filter formatting Haskell code fragments using GHC lexer."
description: |
  Formats marked code fragments, and allows `pandoc` to safely process rest of your literate program:
  .
  > ```{.haskell}
  .
  .
  Usage:
  .
  > stack install pandoc-filter-indent
  > pandoc --filter pandoc-filter-indent -f input.md -o output.pdf
  > pandoc --filter pandoc-filter-indent -f input.md -o output.html
  .
  Using `lhs2TeX` is somewhat inconvenient on large Markdown documents
  processed with `pandoc`, since it assumes that it can freely redefine everything.
  It is also pretty heavy on learning.
  .
  So instead we have a simple Pandoc filter that is only applied to `CodeFragment`s
  and creates tabular code structures from indentation.
  It uses GHC lexer to assure that latest features are always parsed correctly.
  .
  Please see the README on GitHub at <https://github.com/mgajda/pandoc-filter-indent#readme>

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- ghc-syntax-highlighter == 0.0.5.0
- text == 1.2.4.0
- blaze-html == 0.9.1.2
- blaze-markup
- HaTeX
- pandoc-types
- optics-core
- optics-th

library:
  source-dirs: src

executables:
  pandoc-filter-indent:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pandoc-filter-indent
    - optparse-applicative
    - containers

tests:
  pandoc-filter-indent-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pandoc-filter-indent
    - QuickCheck
    - quickcheck-text
